### ISSUE TITLE
cluster-addon-values are not templated

### ISSUE THREAD

**Issue by chess-knight** [SovereignCloudStack/csctl#116]
/kind bug

**What steps did you take and what happened:**
1. Create `cluster-addon-values.yaml`, e.g.:
```yaml
values: |
  metrics-server:
    commonLabels:
      domain: "{{ .Cluster.spec.controlPlaneEndpoint.host }}"
      clusterAddonVersion: "<< .ClusterAddonVersion >>"
```
2. Run `csctl create ...`
3. `cluster-addon-values.yaml` asset is without change

**What did you expect to happen:**
```yaml
values: |
  metrics-server:
    commonLabels:
      domain: "{{ .Cluster.spec.controlPlaneEndpoint.host }}"
      clusterAddonVersion: "v2"
```

**Anything else you would like to add:**
It was mentioned also in https://github.com/SovereignCloudStack/cluster-stacks/pull/43#discussion_r1532772264

**Environment:**

- csctl version: (use `csctl version`)
- OS (e.g. from `/etc/os-release`):
